name: Build database

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install requirements
        run: pip install -r requirements.txt
      - name: build database
        run: |
          make -j 4 nlrb.sqlite
      - name: setup directory
        run: |
          mkdir public
          zip nlrb.sqlite.zip nlrb.sqlite
          mv nlrb.sqlite.zip public
      - name: Github Pages Deploy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./public
